# Generated by Django 5.2 on 2025-04-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_consumer_supplier_user_user_type_consumerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('quality', models.CharField(choices=[('value', 'Value'), ('select', 'Select'), ('premium', 'Premium')], max_length=50)),
                ('supplier_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplierprofile')),
                ('produce_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produce.producetype')),
            ],
        ),
    ]
