# Generated by Django 5.2 on 2025-04-24 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produceitem',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='produceitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='produceitem',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='producetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce/types/'),
        ),
    ]
