# Generated by Django 5.2 on 2025-04-25 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0002_alter_produceitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceitem',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
