# Generated by Django 5.2 on 2025-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0005_producetype_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='produce/items/'),
        ),
    ]
