# Generated by Django 5.2 on 2025-04-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0006_produceitem_item_image'),
        ('produce', '0007_rename_user_produceitem_supplier_profile'),
    ]

    operations = [
    ]
