# Generated by Django 5.2 on 2025-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce', '0008_merge_20250426_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceitem',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
