# Generated by Django 5.2 on 2025-04-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_consumerprofile_user_customeraddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='delivery_address',
        ),
    ]
