# Generated by Django 5.2 on 2025-04-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customerprofile_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierprofile',
            name='location_address',
        ),
    ]
